[development]
address = "0.0.0.0"
port = 8070
workers = 16
log = "critical"

[staging]
address = "0.0.0.0"
port = 8070
workers = 16
log = "critical"

[production]
address = "0.0.0.0"
port = 8070
workers = 16
log = "critical"
